FROM python:3.13

ADD src/DiscordClass.py .
ADD src/FlaskClass.py .
ADD src/main.py .
ADD src/NocoClass.py .
ADD src/TwilioClass.py .
ADD src/wsgi.py .
RUN pip install flask twilio dotenv rich requests discord uwsgi

CMD ["python", "main.py"]
# CMD ["python", "uwsgi --socket 0.0.0.0:80 --protocol=http -w wsgi:app  "]