FROM python:3.13-alpine

ADD src/DiscordClass.py .
ADD src/main.py .
ADD src/NocoClass.py .
ADD src/TwilioClass.py .
ADD src/config.py .
RUN pip install twilio rich requests discord pyyaml typing pydantic

CMD ["python", "main.py"]
