FROM python:3.13

WORKDIR /app

ADD src/FlaskClass.py .
ADD src/NocoClass.py .
ADD src/TwilioClass.py .
ADD src/wsgi.py .

RUN pip install flask twilio dotenv rich requests uwsgi

EXPOSE 80
CMD ["uwsgi", "--socket", "0.0.0.0:80", "--protocol=http", "-w", "wsgi:app"]